# Generated by Django 3.1 on 2020-08-18 04:22

import assignment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phn_no', models.CharField(max_length=12, validators=[assignment.models.phn_no_validation], verbose_name='Mobile No.')),
                ('active', models.BooleanField(default=False)),
                ('client', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_desc', models.TextField(verbose_name='Request Desc')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(choices=[('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('Rajasthan', 'Rajasthan'), ('Maharastra', 'Maharastra'), ('Utter Pradesh', 'Utter Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Gujrat', 'Gujrat'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerela', 'Kerela'), ('Karnatka', 'Karnatka'), ('Orissa', 'Orissa')], max_length=255)),
                ('pincode', models.CharField(max_length=6, validators=[assignment.models.validate_pin], verbose_name='Pin Code')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=255, null=True, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('request_type', models.ManyToManyField(to='assignment.Category_type', verbose_name='Request Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
