# Generated by Django 3.1 on 2020-08-17 09:01

import assignment.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phn_no', models.CharField(max_length=12, validators=[assignment.models.phn_no_validation], verbose_name='Mobile No.')),
                ('active', models.BooleanField(default=False)),
                ('client', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electricity', 'Electricity'), ('Painting', 'Painting'), ('Deep Cleaning', 'Deep Cleaning')], max_length=255, verbose_name='Request Type')),
                ('request_desc', models.TextField(verbose_name='Request Desc')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(choices=[('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('Rajasthan', 'Rajasthan'), ('Maharastra', 'Maharastra'), ('Utter Pradesh', 'Utter Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Gujrat', 'Gujrat'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerela', 'Kerela'), ('Karnatka', 'Karnatka'), ('Orissa', 'Orissa')], max_length=255)),
                ('pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Pin Code')),
                ('country_code', models.CharField(max_length=3, verbose_name='Country Code')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('mobile', models.CharField(max_length=10, validators=[assignment.models.phn_no_validation], verbose_name='Alternate Phone N.')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=255, null=True, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
