# Generated by Django 3.1 on 2020-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200817_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='request_table',
            name='request_type',
        ),
        migrations.AddField(
            model_name='request_table',
            name='request_type',
            field=models.ManyToManyField(to='assignment.Category_type', verbose_name='Request Type'),
        ),
    ]
