# Generated by Django 3.1 on 2020-08-17 15:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20200817_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_table',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='request_table',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
